import type { Metadata } from "next";
// import { IBM_Plex_Sans } from "next/font/google";
import "./globals.css";

// const ibmPlexSans = IBM_Plex_Sans({
// 	variable: "--font-ibm-plex-sans",
// 	subsets: ["latin"],
// 	weight: ["100", "200", "300", "400", "500", "600", "700"],
// });

export const metadata: Metadata = {
	title: "Tashi Exports",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<head>
				<link
					rel="icon"
					href="/favicon.ico"
					sizes="32x32"
					type="image/x-icon"
				/>
			</head>
			<body className="relative w-screen overflow-x-hidden   flex min-h-screen  flex-col justify-center  scroll-smooth bg-background font-sans antialiased">
				<div className="relative flex min-h-screen flex-col bg-background">
					{children}
				</div>
			</body>
		</html>
	);
}
